EC2:
  CPUUtilization:
    period: 300
    evaluation_periods: 3
  MemoryUtilization:
    period: 300
    evaluation_periods: 2
  DiskSpaceUtilization:
    period: 300
    evaluation_periods: 2

RDS:
  CPUUtilization:
    period: 300
    evaluation_periods: 3
  FreeStorageSpace:
    period: 3600
    evaluation_periods: 1

FSx:
  FreeDataStorageSpace:
    period: 3600
    evaluation_periods: 2

NLB:
  UnHealthyHostCount:
    period: 60
    evaluation_periods: 3
