CAT_A:
  description: "Most Critical Systems"
  sns_topic_arns:
    - HIPNotifySpokeCMSTopicLow
  thresholds:
    EC2:
      CPUUtilization: 70
      mem_used_percent: 75
      StatusCheckFailed: 1
      disk_used_percent: 80
      LogicalDisk % Free Space: 20

    RDS:
      CPUUtilization: 65
      FreeStorageSpace: 20

CAT_B:
  description: "Most Critical Systems"
  sns_topic_arns:
    - HIPNotifySpokeCMSTopicLow
  thresholds:
    EC2:
      CPUUtilization: 70
      mem_used_percent: 75
      StatusCheckFailed: 1
      disk_used_percent: 80
      LogicalDisk % Free Space: 20

    RDS:
      CPUUtilization: 65
      FreeStorageSpace: 20
