disabled_alarms:
  cmsnonprod:
    EC2:
      - CPUUtilization
      - MemoryUtilization
    RDS:
      - CPUUtilization

sns_mappings:
  EC2:
    StatusCheckFailed:
      categories: ['CAT_A', 'CAT_B']
      sns_topic: 'HIPNotifySpokeCMSTopicHigh'
    MemoryUtilization:
      categories: ['CAT_C']
      sns_topic: 'HIPNotifySpokeCMSTopicHigh'

# custom_thresholds:
#   CAT_A:
#     EC2:
#       CPUUtilization: 90
#       MemoryUtilization: 85
#   CAT_B:
#     RDS:
#       DatabaseConnections: 100 