disabled_alarms:
  cmsnonprod:
    EC2:
      - CPUUtilization
      - MemoryUtilization
    RDS:
      - CPUUtilization

sns_mappings:
  EC2:
    StatusCheckFailed:
      categories: ["CAT_A", "CAT_B"]
      sns_topics:
        - HIPNotifySpokeCMSTopicHigh
    MemoryUtilization:
      categories: ["CAT_C"]
      sns_topics:
        - HIPNotifySpokeCMSTopicHigh
# metrics:
#   - name: "disk_used_percent"
#     diffrentiate: "path"
#     namespace: "CWAgent"
#   - name: "LogicalDisk % Free Space"
#     namespace: "CWAgent"
