EC2:
  CPUUtilization:
    namespace: "AWS/EC2"
    statistic: "average"
    comparison: "GreaterThanThreshold"
    unit: "Percent"
    period: 300
    evaluation_periods: 3
  MemoryUtilization:
    namespace: "AWS/EC2"
    statistic: "average"
    comparison: "GreaterThanThreshold"
    unit: "Percent"
    period: 300
    evaluation_periods: 2
  DiskSpaceUtilization:
    namespace: "AWS/EC2"
    statistic: "average"
    comparison: "GreaterThanThreshold"
    unit: "Percent"
    period: 300
    evaluation_periods: 2

RDS:
  CPUUtilization:
    namespace: AWS/RDS
    statistic: average
    comparison: "GreaterThanThreshold"
    unit: "Percent"
    period: 300
    evaluation_periods: 3
  FreeStorageSpace:
    namespace: AWS/RDS
    statistic: average
    comparison: "GreaterThanThreshold"
    unit: "Percent"
    period: 3600
    evaluation_periods: 1
# FSx:
#   FreeDataStorageSpace:
#     period: 3600
#     evaluation_periods: 2

# NLB:
#   UnHealthyHostCount:
#     period: 60
#     evaluation_periods: 3
