# Category A - Most Critical Systems
CAT_A:
  - resource_type: EC2
    thresholds:
      CPUUtilization: 70
      MemoryUtilization: 75
      DiskSpaceUtilization: 80
      StatusCheckFailed: 1

  - resource_type: RDS
    thresholds:
      CPUUtilization: 65
      FreeStorageSpace: 20
# Category B - Business Critical Systems
CAT_B:
  - resource_type: EC2
    thresholds:
      CPUUtilization: 70
      MemoryUtilization: 75
      DiskSpaceUtilization: 80
      StatusCheckFailed: 1

  - resource_type: RDS
    thresholds:
      CPUUtilization: 65
      FreeStorageSpace: 20