- name: Set EC2-specific variables
  ansible.builtin.set_fact:
    resource_name: "{{ resource_name }}"
    resource_id: "{{ resource_id }}"
    # ec2_cpu_threshold: "{{ ec2_cpu_threshold | default(85) }}"
    # ec2_memory_threshold: "{{ ec2_memory_threshold | default(75) }}"
    # ec2_disk_threshold: "{{ ec2_disk_threshold | default(80) }}"
    metric_thresholds: "{{ metric_thresholds }}"
    evaluation_periods: "{{ evaluation_periods | default(2) }}"
    period: "{{ period | default(300) }}"

- name: Include CloudWatch Alarms role for EC2
  ansible.builtin.include_role:
    name: cloudwatch_alarms
