---
- name: Deploy CloudWatch Alarms for AWS Resources
  hosts: localhost
  connection: local
  vars:
    resource_type: "{{ resource_type }}" # Set to "rds" as needed
    sns_topics: "{{ sns_topics }}"
  tasks:
    - name: Deploy EC2 CloudWatch Alarms
      when: resource_type == "EC2"
      block:
        - name: Include EC2 Alarm Tasks
          ansible.builtin.include_tasks: "roles/cloudwatch_alarms/tasks/ec2_alarms.yml"

    - name: Deploy RDS CloudWatch Alarms
      when: resource_type == "RDS"
      block:
        - name: Include RDS Alarm Tasks
          ansible.builtin.include_tasks: "roles/cloudwatch_alarms/tasks/rds_alarms.yml"
